### ISSUE TITLE
Use all of corpus in frelatage input

### ISSUE THREAD

**Issue by CityOfLight77** [Rog3rSm1th/Frelatage#13]
If we have thousands or more corpus, can we use all of corpus in the input directory instead of define filenames manually in `frelatage.Input(file=True, value="filename")` ?

**Comment by Rog3rSm1th** [comment]
Thanks for this feature idea !

It is now possible to load several files at once as described [here](https://github.com/Rog3rSm1th/Frelatage#load-several-files-to-a-corpus-at-once).
