### ISSUE TITLE
How to use inf values?

### ISSUE THREAD

**Issue by ghost** [Rog3rSm1th/Frelatage#28]
Update docs and tell us how to use inf values for settings

**Comment by Rog3rSm1th** [comment]
For each option taking numerical value it is possible to specify any integer from 0 to infinity using the environment variables. 

Concerning the infinite fuzzing it is now possible to activate it by passing ```infinite_fuzz=False``` to the Fuzzer during the instantiation as explained [here](https://github.com/Rog3rSm1th/Frelatage#passing-arguments-to-the-fuzzer).
